# Generated by Django 5.2.8 on 2025-11-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_nickname",
                    models.CharField(
                        default="", max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(default="", max_length=150)),
                ("email", models.EmailField(default="", max_length=254)),
                ("user_age", models.IntegerField(default=0)),
            ],
        ),
    ]
